"""Atualizando os models

Revision ID: 4786654109e2
Revises: 4902f3e88e56
Create Date: 2024-10-31 20:49:51.891255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4786654109e2'
down_revision = '4902f3e88e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitantes', schema=None) as batch_op:
        batch_op.drop_column('data_visita')

    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['data'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('visitantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_visita', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
